layout_spectrum: 0.2148936
color:
  saturation: 0.8957447
  brandStrength: 0.6734467
  lightness: 0
  rhythmicContrast: 0.7723404
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
typography_spectrum: 0.8170213
name: Mortgagejake
